const views=[...document.querySelectorAll('.account-view')];const nav=[...document.querySelectorAll('.account-nav button')];const toast=document.querySelector('#toast');let timer;const key='luxAccount';
function showToast(message){clearTimeout(timer);toast.textContent=message;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),3200)}
function showView(name){views.forEach(v=>v.classList.toggle('is-active',v.id===`view-${name}`));nav.forEach(b=>b.classList.toggle('is-active',b.dataset.view===name));if(name==='restock')renderRestock()}
nav.forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
let authMode='register';document.querySelectorAll('[data-auth]').forEach(b=>b.addEventListener('click',()=>{authMode=b.dataset.auth;document.querySelectorAll('[data-auth]').forEach(x=>x.classList.toggle('is-active',x===b));document.querySelector('#account-submit').textContent=authMode==='register'?'無料で登録する':'ログインする';document.querySelector('#account-name').closest('label').hidden=authMode==='login'}));
const form=document.querySelector('#account-form');form.addEventListener('submit',e=>{e.preventDefault();let valid=true;form.querySelectorAll('[required]').forEach(input=>{if(input.closest('label').hidden)return;const error=input.closest('label').querySelector('.field-error');error.textContent='';if(!input.value.trim()||!input.checkValidity()){error.textContent=input.type==='email'?'正しいメールアドレスを入力してください。':input.type==='password'?'8文字以上で入力してください。':'入力してください。';valid=false}});if(!valid){form.querySelector(':invalid')?.focus();return}const existing=JSON.parse(localStorage.getItem(key)||'null');const data={name:document.querySelector('#account-name').value||existing?.name||'ゲスト',email:document.querySelector('#account-email').value};localStorage.setItem(key,JSON.stringify(data));updateAuth();showToast(authMode==='register'?'デモアカウントを登録しました。':'ログインしました。')});
function updateAuth(){const account=JSON.parse(localStorage.getItem(key)||'null');document.querySelector('#signed-out').hidden=!!account;document.querySelector('#signed-in').hidden=!account;if(account){document.querySelector('#profile-name').textContent=account.name;document.querySelector('#profile-email').textContent=account.email}}
document.querySelector('#logout-button').addEventListener('click',()=>{localStorage.removeItem(key);updateAuth();showToast('ログアウトしました。')});
const prefs=JSON.parse(localStorage.getItem('luxPrefs')||'{}');document.querySelectorAll('[data-pref]').forEach(input=>{if(input.dataset.pref in prefs)input.checked=prefs[input.dataset.pref];input.addEventListener('change',()=>{const next={};document.querySelectorAll('[data-pref]').forEach(x=>next[x.dataset.pref]=x.checked);localStorage.setItem('luxPrefs',JSON.stringify(next));showToast('通知設定を保存しました。')})});
const pushState=document.querySelector('#push-state');const pushButton=document.querySelector('#enable-push');function updatePush(){if(!('Notification'in window)){pushState.textContent='このブラウザは通知機能に対応していません。';pushButton.disabled=true;return}pushState.textContent=Notification.permission==='granted'?'この端末では通知が許可されています。':Notification.permission==='denied'?'端末またはブラウザ設定で通知が拒否されています。':'まだ通知を許可していません。';pushButton.textContent=Notification.permission==='granted'?'テスト通知を表示':'通知を許可する'}
pushButton.addEventListener('click',async()=>{if(!('Notification'in window))return;const permission=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;updatePush();if(permission==='granted'){const registration=await navigator.serviceWorker?.ready;registration?.showNotification('Lux Canis',{body:'通知設定が完了しました。新作や再販情報をここで受け取れます。',icon:'./assets/item-03.webp'});showToast('テスト通知を表示しました。')}});
function renderRestock(){const list=document.querySelector('#restock-list');const items=JSON.parse(localStorage.getItem('luxRestock')||'[]');if(!items.length){list.innerHTML='<div class="empty-card"><strong>再販待ちの商品はありません</strong><p>売り切れ商品の詳細ページから登録できます。</p><a class="button button-primary" href="./index.html#items">商品を見る</a></div>';return}const imageMap={'tiny-drop':'item-04.webp'};list.innerHTML=items.map(item=>`<article class="restock-item"><img src="./assets/${imageMap[item.id]||'item-04.webp'}" alt=""><div><strong>${item.name}</strong><p>${item.color} / 再販待ち登録中</p></div><button type="button" data-remove="${item.id}">登録を解除</button></article>`).join('');list.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('luxRestock',JSON.stringify(items.filter(x=>x.id!==b.dataset.remove)));renderRestock();showToast('再販通知を解除しました。')}))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');updateAuth();updatePush();renderRestock();
